### ISSUE TITLE
Consistent error in the use of `'`

### ISSUE THREAD

**Issue by KennethEnevoldsen** [UniversalDependencies/UD_Danish#4]
Seems like there is a consistent error in the use of `'`. Searching through the dataset I see a bunch of places where spaces lack:

```
Den klub mente Lars'far var sagen --> Den klub mente Lars' far var sagen
```

This might be an error from the original author, but within the entire DDT there is not single instance of ' being followed by a whitespace which seems to indicate that there might have been a mistaken autocorrection as some point in time.

Let me know if I am missing something. 

PS: I have a manually corrected version, let me know if you want it.

**Comment by dan-zeman** [comment]
> I have a manually corrected version, let me know if you want it.

Can you submit it as a pull request (based on the `dev` branch and submitted with `dev` branch as the target)? Thanks!

**Comment by KennethEnevoldsen** [comment]
Perfect I have done that.

**Comment by dan-zeman** [comment]
Thanks! Merged into dev, valid. (It will be merged into master during release time next month.)

**Comment by KennethEnevoldsen** [comment]
Perfect - looking forward!
